//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen
    {
        public System.Guid CitizenId { get; set; }
        public string NationalID { get; set; }
        public Nullable<bool> Sex { get; set; }
    
        public virtual User User { get; set; }
    }
}
